services:
  launcher:
    build: .
    container_name: launcher
    restart: unless-stopped
    environment:
      PORT: 8000
      CONFIG_PATH: /app/config.json # Dejamos la ruta fija dentro del contenedor
    volumes:
      # Esta línea es la magia: mapea de forma dinámica el archivo externo usando una variable
      - ${LAUNCHER_CONFIG_FILE:-./config.json}:/app/config.json:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launcher.rule=PathPrefix(`/`)"
      - "traefik.http.routers.launcher.entrypoints=web"
      - "traefik.http.services.launcher.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true