services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      # Puntos de entrada para el tráfico
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      # Configuración del desafío DNS con DuckDNS (Let's Encrypt)
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=duckdns
      - --certificatesresolvers.myresolver.acme.email=largoguns@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    environment:
      - PROXY_HTTP_PORT=${PROXY_HTTP_PORT:-80}
      - DOCKER_API_VERSION=1.40
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN} # <- Aquí lee de forma segura tu variable oculta
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
      - "8443:443" # Puerto seguro HTTPS externo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - proxy

volumes:
  letsencrypt:

networks:
  proxy:
    external: true